version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
  app:
    container_name: django_app
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/sms_sending
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - .env
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
  celery:
    container_name: celery
    build: .
    restart: always
    command: celery worker --app=core --loglevel=info
    volumes:
      - .:/sms_sending
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - app
      - db
  dashboard:
    container_name: dashboard
    build: .
    command: flower --app=core --port=5555 broker=redis://redis:6379/0
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - app
      - celery 
