FROM python:latest
ENV PYTHONUNBUFFERED 1
ENV DJANGO_ENV dev
ENV DOCKER_CONTAINER 1

COPY ./requirements.txt /sms_sending/requirements.txt
RUN pip install -r /sms_sending/requirements.txt

COPY . /sms_sending/
WORKDIR /sms_sending/

EXPOSE 8000
EXPOSE 5555